machines:
- device_type: linux
  name: gw
  networks:
  - bridge: '**vmbr0**'
  - bridge: hq
  replicas:
    pve2: '101'
    pve3: '102'
    srv2: '102'
    srv3: '101'
  template_node: pve1
  template_vmid: 100
- device_type: linux
  name: hq
  networks:
  - bridge: hq.100
  replicas:
    pve2: '101'
    pve3: '102'
    srv2: '102'
    srv3: '101'
  template_node: pve1
  template_vmid: 100
